# <span style="color : #9e7efe;">예외
## <span style="color : #9efe5e;">Throwable
* Throwable 클래스는 던질 수 있는이라는 의미로 자바 내에서 발생시킬 수 있는 일반적인 의미의 오류의 최상위 타입이다.
### Error
* Error 클래스는 Throwable 을 상속 받아 자바 실행 중 발생할 수 있는 환경 요인에 대한 오류를 구현한다
* 일반적으로 개발자의 개발 실수로 인해 발생하는 문제를 구현하지 않는다. 주로 하드웨어의 메모리 부족이나 가상 환경(JVM)에 치명적인 오류가 있을 때 발생한다
* Unchecked Throwable로 별도의 명시나 처리 없이 발생 시킬수 있다
* 개발자가 직접 Error 클래스를 상속 받아 사용자 정의 Error 를 만들거나 고의로 발생시키는 것은 권장되지 않는다.
* Error 클래스를 상속 받는 대표적인 예
    * OutOfMemoryError : 가상 머신에 할당된 메모리가 부족하여 발생하는 Error
    * StackOverflowError : 스택 오버플로우 때문에 발생하는 Error
    * VirtualMachineError : 가상 환경(JVM)과 관련된 문제로 발생하는 에러
### Exception
* Exception 클래스는 Throwable 을 상속 받아 자바 실행 중 발생할 수 있는 일반적인 오류를 구현한다
* 예외는 크게 RuntimeException 을 상속 받는 것과 그렇지 않은 것 두 가지로 분류할 수 있다
* 사용자 정의 오류가 필요하다면 Exception 혹은 RuntimeException 을 상속 받아 사용하는 것이 좋다
#### RuntimeException 을 상속 받는 것
* Unchecked Throwable 로 별도의 명시나 처리 없이 발생시킬 수 있다.
* 대표적인 예
    * NullPointerException : 참조 타입의 변수가 가리키고 있는 힘의 주소가 없는 경우(스택 값이 없는 경우)에서 이의 멤버에 접근하려 했을 때 발생한다
    * ArrayIndexOutOfBoundsException : 배열 등에서 그 순번을 벗어난 인덱스에 대해 접근하려 했을 때 발생한다
    * ArithmeticException : 수학 및 사칙연산과 관련하여 문제가 있을때 발생한다
    * NumberFormatException : Integer.parseInt 등의 메서드를 통해 숫자가 아닌 문자열을 숫자로 변형하려 할 때 발생한다

#### RuntimeException 을 상속 받지 않는 것
* **checked** throwable로 별도의 명시나 처리가 있어야 발생시킬 수 있다
* 대표적인 예
    * IOException : 파일 등의 입출력과 관련하여 오류가 있을 때 발생한다
    * InterruptedException : 사용자 등에 의해 스레드 등의 실행이 중단(방해)되었을 때 발생한다.
    * TimeOutException : 어떠한 작업에 대해 제한된 시간이 초과되었을 때 발생한다.
### Throwable 발생 시키기
* 고의로 throwable 을 발생시키기 위해 throw 키워드를 활용한다
>```java
>throw [Throwable을 상속 받는 객체];
>```
>* 가령 NumberFormatException 을 고의로 발생 시키기 위해 아래와 같이 작성한다
>```java
>throw new NumberFormatException();
>```
* 단, 발생시키고자 하는 throwable 이 Checked Throwable
### Try-Catch
* try...Catch 문은 try 가 가지는 구현부 안에서 발생하는 오류에 대해 오류를 발생시키지 않고 catch 에서 원하는 로직을 실행하기 위해 사용한다
* try...catch 문의 구조는 아래와 같다
>```java
>try {
>    [오류 발생 가능성이 높은 구현부]
>} catch ([처리할 예외 1 선언]) {
>    [예외 1 발생시 구현부]
>} catch ([처리할 예외 2 선언]) {
>    [예외 2 발생시 구현부]
>} catch ([처리할 예외 3 선언]) {
>    [예외 3 발생시 구현부]
>} finally {
>    [최종 구현부]
>}
>```
>* catch 문은 여러 개 작성할 수 있다. 단, 보다 선행하는 예외가 후행하는 예외보다 부모여서는 안된다
>* catch 하는 예외가 Checked 일 경우 해당 예외를 던질 수 있는 로직이 try 내부에 반드시 구현되어 있어야 한다
>* catch 하는 예외가 Unchecked 일 경우 해당 예외를 던질 수 있는 로직이 try 내부에 반드시 있어야 하는 것은 아니다
>* finally 문은 선택사항이다. 이가 가지는 구현부는 **try 를 정상 실행 하든 catch로 빠졌든 `반드시 실행됨`을 보장 받는다**. 모든 catch 보다 아래에 있어야 하고 **없거나, 하나만 사용할 수 있다**

>* Throwable 
>>* Error
>>* Exception